FROM asoltys/raretoshi:base

ARG NODE_ENV=staging
ENV NODE_ENV $NODE_ENV

WORKDIR /app
COPY . .
RUN sed -i '/cypress/d' package.json
RUN cp .env.staging .env.production
RUN mv /deps/node_modules /app
RUN pnpm build

CMD ["node", "build"]
