FROM node:17-alpine

RUN apk add git python3 build-base sed
RUN npm i -g pnpm

WORKDIR /deps
COPY package.json .
COPY .pnpmfile.cjs .
RUN sed -i '/cypress/d' package.json
RUN NODE_ENV=development pnpm i
