FROM gcr.io/coinos-326717/github.com/tokenocean/raretoshi:base

ARG NODE_ENV=staging
ENV NODE_ENV $NODE_ENV

WORKDIR /app
COPY . .
RUN sed -i '/cypress/d' package.json
RUN sed -i 's/raretoshi.com/raretoshi.blockstream.com/g' .env.production
RUN mv /deps/node_modules /app
RUN pnpm build

CMD ["node", "build"]
