-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- update editions set owner_id = (select owner_id from artworks where artworks.id = editions.artwork_id);
