-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."open_editions" add column "minted" boolean
--  not null default 'false';
