-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- delete from artworks where edition > 1;
-- alter table "public"."artworks" drop column "edition" cascade;
